# Generated by Django 3.1.7 on 2021-03-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
